excludes = [".envrc", "*.lock", ".gitignore"]
on-unmatched = "warn"

[formatter.alejandra]
command = "alejandra"
includes = ["*.nix"]

[formatter.keep-sorted]
command = "keep-sorted"
includes = ["*"]

[formatter.mdformat]
command = "mdformat"
includes = ["*.md"]

[formatter.rustfmt]
command = "rustfmt"
includes = ["*.rs"]
options = ["--config", "skip_children=true", "--edition", "2024"]

[formatter.taplo]
command = "taplo"
includes = ["*.toml"]
options = ["format"]

[formatter.yamlfmt]
command = "yamlfmt"
includes = ["*.yaml", "*.yml"]
